### ISSUE TITLE
Unit Testing Framework

### ISSUE THREAD

**Issue by arlanz** [nhs-robotics/t-10-code#4]

**Comment by arlanz** [comment]
JUnit working - congratulations @liambridgers!

**Comment by AncientBison** [comment]
#20 added github action for tests

**Comment by lllincoln** [comment]
Complete? @liambridgers @AncientBison

**Comment by AncientBison** [comment]
Up to you. Either:
- we complete this issue after writing the framework for unit tests
or
- we never complete this issue and leave it open as a reminder to write tests for new code (and the rest that is already there)

@arlanz @liambridgers @YoungerMax

**Comment by lllincoln** [comment]
> Up to you. Either:
> - we complete this issue after writing the framework for unit tests
> or
> - we never complete this issue and leave it open as a reminder to write tests for new code (and the rest that is already there)
> 
> @arlanz @liambridgers @YoungerMax 

Let's go with the first option. Are the unit tests done? What's progress looking like on those?

**Comment by AncientBison** [comment]
We got 1 suite up mostly as an example as to write other tests

**Comment by lllincoln** [comment]
Excellent work by @liambridgers in [4fc6205](https://github.com/nhs-robotics/t-10-code/commit/4fc6205bbdf325e7b17515c9c7cc4b69c220c90e). Kudos to @liambridgers and @AncientBison! This is complete! 👏
